### ISSUE TITLE
CloudFlare Available Domains Blank

### ISSUE THREAD

**Issue by MagnusBou** [Alexr03/TCAdminSubdomain#1]
Hi,
I can't figure out how to get the list with "Available Domains", to show our domains from CloudFlare.
I've filled in my token, that was created like the wiki said, saved and updated the page. - But to no success.

Do you have any ideas on how to fix this?

Thanks you so much!

![image](https://user-images.githubusercontent.com/44668223/97093779-31489580-164f-11eb-940e-3bd4aeb2c0b4.png)

![image](https://user-images.githubusercontent.com/44668223/97093770-27bf2d80-164f-11eb-9efa-f73484d23a64.png)

**Comment by MagnusBou** [comment]
It seems to be working after a complete system restart.

**Comment by Alexr03** [comment]
Thanks for letting me know.
