### ISSUE TITLE
Find a old configuration

### ISSUE THREAD

**Issue by numpty9989** [Alexr03/TCAdminSubdomain#5]
i messed up and had to get a new API key as i accidently deleted my old one :( but now ones that are made are not deleting comes wioth an eerror of https://i.imgur.com/6C6zvR8.png is there anywhere in the database or anythin gwhere it saves the subdomains as i have tried removing and reinstalling plugin but the subdomain remoans i am wondering if there is wherner i can delete a subdomain and start fresh as this customer wants to change his sub domain and now cannot due to this pleas ehelp m,e

**Comment by Alexr03** [comment]
Hi, Email me at alexredding180@gmail.com or message me on discord Alexr03#1525 with a temporary login to your TCAdmin and a service URL where this is happening

**Comment by Alexr03** [comment]
If you want to try and just delete the subdomains, goto `tc_game_services` table and find the service
Edit the Variables tab and remove these lines: 
```
  <add key="SD-FullSubDomain" value="xxxx" type="System.String,mscorlib" />
  <add key="SD-ZoneId" value="xxxx" type="System.String,mscorlib" />
  <add key="SD-DnsProvider" value="xxxx" type="System.Int32,mscorlib" />
```
